### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "90d8c520a4f0b035ac51e267a8b33739c5a78b5a";
          sha256 = "05i74sl5i6abblx8xkd4sm0wbwafarlpry84wg6q52ff70shhdlq";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.13.1";
  selection = 
  {
    angstrom = 
    {
      pname = "angstrom";
      version = "0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/angstrom/archive/0.16.0.tar.gz";
        sha256 = "1w0hhkdnsbyhpkkacyj5k7dbvy5n3idzkcryr057rm862g9hp0a7";
      };
      opamInputs = 
      {
        inherit (selection) ocaml-syntax-shims ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/angstrom/angstrom.0.16.0";
        hash = "sha256:11h41rci304yznw6v9l2kag6vs4lfn0zcd9mcx8mnjpb4hq05lfh";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "050syrp6v00gn50d6xvwv6a36zsk4zmahymgllxpw9paf4qk0pkm";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.15.1";
        hash = "sha256:0gx21y0rnza0dqj3i1fdblf9n3cd56awyd9md3dd8v41f1fvqi97";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    bigstringaf = 
    {
      pname = "bigstringaf";
      version = "0.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.9.1.tar.gz";
        sha256 = "02smd8d2iv47r5a150nj3angxfp1vwc5474la1jqp68lsrvr5yc7";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigstringaf/bigstringaf.0.9.1";
        hash = "sha256:1f0g6rfnws5pkimpm11pnr8xnq1jw2vhajv6czg3j2n2qndag3a8";
      };
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
      };
    };
    conf-libcurl = 
    {
      pname = "conf-libcurl";
      version = "2";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-libcurl/conf-libcurl.2";
        hash = "sha256:19yg08b6m2kd22r521nxswwm6a1jaqbn4bbn2g1g53dh67pwpn70";
      };
      buildInputs = [ (pkgs.curl) ];
    };
    containers = 
    {
      pname = "containers";
      version = "3.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/ocaml-containers/releases/download/v3.13.1/containers-3.13.1.tbz";
        sha256 = "114pcswmscbh5mvniiarbk5jqma3kjs6w9bx2p2lzw1w5kmjd6zb";
      };
      opamInputs = 
      {
        inherit (selection) ocaml either dune-configurator
        dune;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/containers/containers.3.13.1";
        hash = "sha256:0qljvxcnpgyxsccjmlp315g77nb7sp7iv00p74sw3qr2314vmrgn";
      };
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
        sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.9";
        hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.0/dune-3.14.0.tbz";
        sha256 = "1z5jd1yfkfxppbgd3cxmkwbx48291jjky9ac8bzzs8962s4rvl7l";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.14.0";
        hash = "sha256:1k04jgpz29jdk26l3rc37fxp0x0j3kv3ipyml47f38nhianq2fpq";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.0/dune-3.14.0.tbz";
        sha256 = "1z5jd1yfkfxppbgd3cxmkwbx48291jjky9ac8bzzs8962s4rvl7l";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.14.0";
        hash = "sha256:01w4gs68db729hjnvcx2qra6kskj5fv7llzmdd5bms0akb4krh35";
      };
    };
    either = 
    {
      pname = "either";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/either/releases/download/1.0.0/either-1.0.0.tbz";
        sha256 = "112qa1zdkf4mvn6932jb2rwxdcvfm7lg2zgh2mr7pvid67ilsrxz";
      };
      opamInputs = {
                     inherit (selection) dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/either/either.1.0.0";
        hash = "sha256:1qcj3zl0hjlc4djn5q6qjiagm5xq1q1vgbshwlf4gj7h7kzx11bf";
      };
    };
    ezcurl = 
    {
      pname = "ezcurl";
      version = "0.2.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/ezcurl/releases/download/v0.2.4/ezcurl-0.2.4.tbz";
        sha256 = "18a1allskmw4frg1dhxq27l1krhahmjg4izyzgm4dmvjpq4a5v96";
      };
      opamInputs = {
                     inherit (selection) ocurl ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ezcurl/ezcurl.0.2.4";
        hash = "sha256:0wnnydpwny1gvq5z8y76lm3j1sg2s03pvqs8vm3wg7gg3brvn2v2";
      };
    };
    ezcurl-lwt = 
    {
      pname = "ezcurl-lwt";
      version = "0.2.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/ezcurl/releases/download/v0.2.4/ezcurl-0.2.4.tbz";
        sha256 = "18a1allskmw4frg1dhxq27l1krhahmjg4izyzgm4dmvjpq4a5v96";
      };
      opamInputs = 
      {
        inherit (selection) ocurl ocaml lwt ezcurl dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ezcurl-lwt/ezcurl-lwt.0.2.4";
        hash = "sha256:0p7bb64zg1wim0ihx90qs6mpbx555d34l7x9mcvk0gajgyys9gfl";
      };
    };
    lambdasoup = 
    {
      pname = "lambdasoup";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/aantron/lambdasoup/archive/1.0.0.tar.gz";
        sha256 = "1g5jr1s024z755slz5zg4cssmxqbva0d0nhn75wd09p45v7c94x3";
      };
      opamInputs = 
      {
        inherit (selection) ocaml markup dune camlp-streams;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambdasoup/lambdasoup.1.0.0";
        hash = "sha256:0mzvlsx8gpshz23687vdqmv0sbfkqrqjz5wjiq4bdzj5gap6lk80";
      };
    };
    lang_agent = 
    {
      pname = "lang_agent";
      version = "development";
      src = self.directSrc "lang_agent";
      opamInputs = 
      {
        inherit (selection) yojson uri stdio ppx_yojson_conv_lib
        ppx_yojson_conv ppx_yojson ocaml lwt_ppx lambdasoup ezcurl-lwt ezcurl
        dune containers;
      };
      opamSrc = "lang_agent.opam";
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz";
        sha256 = "11dpr0aprqqjgb2n4j4czpw3l0bc8dzy1jqmp2qz3xkih31k241p";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.7.0";
        hash = "sha256:1fpvcmvrkwaz6w5rshgpw37n10dz9js68i553mmjs1g2g6wdpq73";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.1.0";
        hash = "sha256:09kc2bwmqq41983xivild7az3s62nrhp62iinvc2b6lpcldzvqqc";
      };
    };
    markup = 
    {
      pname = "markup";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/aantron/markup.ml/archive/1.0.3.tar.gz";
        sha256 = "1dbfh21x7gc3irz0xywg4cjb2lid2j3qflp2wrx7vhxgl03gs9lm";
      };
      opamInputs = 
      {
        inherit (selection) uutf uchar ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/markup/markup.1.0.3";
        hash = "sha256:1qnkprbn2lmwkly8l05jrhwj9gmp4di1cfnd4civ69hq3xa6kp4n";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.13.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.13.1";
        hash = "sha256:12aajj2hc636jr6wbv4vba8pmjdndbcvnw7q35gj4agxmrjspziw";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.13.1.tar.gz";
        sha256 = "1i7ad8lh5l74wb3yzmhlv529wc75a5sjybzkad7wdl8zrj47jk0r";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.13.1";
        hash = "sha256:069i5vsndd9lsvdm5wk898nfnc85ww7459nibjg6881ww43w8ck1";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1rn7ai9n2g5xja553qa5r9iamsqmrsnl4h7zkmmbcn27qj7vczsv";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.3.tar.gz";
        sha256 = "1qf21zds8f3izbb9bxwblijgb7wqkrhbl99z1gpcdas147yin5ff";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.3";
        hash = "sha256:0ymzb8ykkbvpzp8swdssr1iw85a0i66vprnxsxy6dpghhpm1rrqs";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    octavius = 
    {
      pname = "octavius";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/octavius/archive/v1.2.2.tar.gz";
        sha256 = "1bg0fcm7haqxvx5wx2cci0mbbq0gf1vw9fa4kkd6jsriw1611jga";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/octavius/octavius.1.2.2";
        hash = "sha256:0bagilkanfjyi56hrk9dw43xs6zry9p8n3l55r3d58v5hz2xsbwl";
      };
    };
    ocurl = 
    {
      pname = "ocurl";
      version = "0.9.2";
      src = pkgs.fetchurl 
      {
        url = "https://ygrek.org/p/release/ocurl/ocurl-0.9.2.tar.gz";
        sha256 = "0qvpsqbq4qbd397n0nlv9cwlqfyjw7gfb5mmq1awvnklr0c9fdg0";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-libcurl
        base-unix;
        lwt_ppx = selection.lwt_ppx or null;
        lwt = selection.lwt or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocurl/ocurl.0.9.2";
        hash = "sha256:00h9bzin4jvrj60davpxiqy9yvkpkqn16i23dw818ak1f2qybiic";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_js_style = 
    {
      pname = "ppx_js_style";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_js_style-v0.15.0.tar.gz";
        sha256 = "1szbizivg20qsvg9xclvccw3g1vpvjfgjfssx5312dgrggwy61cx";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib octavius ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_js_style/ppx_js_style.v0.15.0";
        hash = "sha256:1rrn3vkmbdxabm5ad2c2ipspf9rz32w0jqw2vkw59hs9yjlzw6if";
      };
    };
    ppx_yojson = 
    {
      pname = "ppx_yojson";
      version = "1.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/NathanReb/ppx_yojson/releases/download/1.3.0/ppx_yojson-1.3.0.tbz";
        sha256 = "0vr677smr9cbg0hi9bck9lhkyrf9fjk42k1wylpiwvlxjr3446yz";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson/ppx_yojson.1.3.0";
        hash = "sha256:1fhp7qi97gjv6wmzk8qxnjdcq4nxyl3zx1fm8py33ai2778a518s";
      };
    };
    openai = 
    {
      pname = "openai";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/meta-introspector/openai-ocaml/archive/refs/tags/0.0.2.tar.gz";
      };

      opamInputs = 
      {
        inherit (selection) ppx_yojson_conv ppx_yojson ocaml lwt_ppx
        ezcurl-lwt dune conf-openssl;
      };
      opamSrc = "openai.opam";
    };

    ppx_yojson_conv = 
    {
      pname = "ppx_yojson_conv";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_yojson_conv/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "1kagc5zk3kbnhvwz4bli9v75wwx3mrj7id1bd2r28ninf45d515f";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_yojson_conv_lib ppx_js_style ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv/ppx_yojson_conv.v0.15.1";
        hash = "sha256:16hi3fqcki143h3w5a4rvh9gm2mqnr1l04fz7ava0aar2d64azb6";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_yojson_conv_lib-v0.15.0.tar.gz";
        sha256 = "115nlv3apiwsbay6188916zddpf84bnqdcbrygqw2vjnykpwblpr";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.15.0";
        hash = "sha256:07pckbhr0nbswij1z61mw2qkanz1swp5rns7m04487rkphw2lwa2";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.32.1-5.2preview";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/archive/51851b4f9b18fe75a0bc24c383d5843855de87e3.tar.gz";
        sha256 = "18v03xgn87zrksyk1b3d17srd0hxmrcmbdk7lxg9wxhljbf0diki";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.32.1~5.2preview";
        hash = "sha256:06r59pxdwr2nhvvvjasyyv1640gl2xyk8my96fy1gki66id2r4db";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/sexplib0/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "1cv78931di97av82khqwmx5s51mrn9d2b82z0si88gxwndz83kg8";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.15.1";
        hash = "sha256:1yg5rknfbx67wrs3gampx3jmcw9si38n90cj4kg5626k41nmhsc0";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/stdio-v0.15.0.tar.gz";
        sha256 = "0jsyg4jlp76d9gx1fngms6nfs7dcpsysdsvkywjq9a663n994wn3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.15.0";
        hash = "sha256:19z0wh8sm8ldwwpqq2hxn85b74z1g3jlkx7vfpqknm0pxhill7m1";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stringext = 
    {
      pname = "stringext";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stringext/stringext.1.6.0";
        hash = "sha256:01k5gspcs4i7ipghzm2qsxgmyja86nd224achciny46xdjpkchpd";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.7";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
        sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.7";
        hash = "sha256:1411142m653308lj3nlgbv2wvww2i5hyfdgz94l2b3ga3qdp7szc";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    uri = 
    {
      pname = "uri";
      version = "4.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
        sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
      };
      opamInputs = 
      {
        inherit (selection) stringext ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri/uri.4.4.0";
        hash = "sha256:1jzwbdw5lp3bv1hw9kdi86d0yzzfg5shp0571kw9gkhypisr7jva";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.1.2/yojson-2.1.2.tbz";
        sha256 = "1ydlvw0f50vg8ia9529ldq07d2jyqzjr9230pyywr9y8pymz3wjr";
      };
      opamInputs = 
      {
        inherit (selection) seq ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.1.2";
        hash = "sha256:10cqyg4ykrfc39lfb0xhykknym1pz5saivq3ighgns4a1rnkixf3";
      };
    };
  };
}

