(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class_type` not handled. *)
(* class_type *)

(* ❌ Structure item `class` not handled. *)
(* class *)

(* ❌ Structure item `class` not handled. *)
(* class *)

(* ❌ Structure item `class` not handled. *)
(* class *)

Definition t_key_string : Set := string.

Definition t_address_string : Set := string.

Definition t_model_name : Set := string.

Definition t_temperature_float : Set := Stdlib.Float.t.

Definition t_max_tokens_int : Set := Stdlib.Int.t.

Definition t_system_content_string : Set := string.

Definition t_prompt_string : Set := string.

Definition t_response_string : Set := string.

Module client_t.
  Record record : Set := Build {
    agt_key : t_key_string;
    agt_url : t_address_string;
    agt_model : t_model_name;
    agt_temp : t_temperature_float;
    agt_tokens : t_max_tokens_int;
    agt_system_prompt : t_system_content_string;
  }.
  Definition with_agt_key agt_key (r : record) :=
    Build agt_key r.(agt_url) r.(agt_model) r.(agt_temp) r.(agt_tokens)
      r.(agt_system_prompt).
  Definition with_agt_url agt_url (r : record) :=
    Build r.(agt_key) agt_url r.(agt_model) r.(agt_temp) r.(agt_tokens)
      r.(agt_system_prompt).
  Definition with_agt_model agt_model (r : record) :=
    Build r.(agt_key) r.(agt_url) agt_model r.(agt_temp) r.(agt_tokens)
      r.(agt_system_prompt).
  Definition with_agt_temp agt_temp (r : record) :=
    Build r.(agt_key) r.(agt_url) r.(agt_model) agt_temp r.(agt_tokens)
      r.(agt_system_prompt).
  Definition with_agt_tokens agt_tokens (r : record) :=
    Build r.(agt_key) r.(agt_url) r.(agt_model) r.(agt_temp) agt_tokens
      r.(agt_system_prompt).
  Definition with_agt_system_prompt agt_system_prompt (r : record) :=
    Build r.(agt_key) r.(agt_url) r.(agt_model) r.(agt_temp) r.(agt_tokens)
      agt_system_prompt.
End client_t.
Definition client_t := client_t.record.

Definition mk_client_t : client_t :=
  {| client_t.agt_key := ""; client_t.agt_url := ""; client_t.agt_model := "";
    client_t.agt_temp :=
      (* ❌ Float constant 0.0 is approximated by the integer 0 *)
      0; client_t.agt_tokens := 128;
    client_t.agt_system_prompt := "You are legion"; |}.

(* ❌ Structure item `class` not handled. *)
(* class *)
